### ISSUE TITLE
Automatic KIE Server Configuration Not Compatible With Docker Compose 2+

### ISSUE THREAD

**Issue by Shumakriss** [jboss-dockerfiles/drools#21]
I am testing integration between jBPM Workbench Showcase and KIE Server Showcase Docker images.  I followed the instructions and ran: 

docker run -p 8080:8080 -p 8001:8001 -d --name jbpm-workbench jboss/jbpm-workbench-showcase:latest
docker run -p 8081:8080 -d --name kie-server --link jbpm-workbench:kie_wb jboss/kie-server-showcase:6.5.0.Final

This works great!

However, using docker-compose.yml at v2, this does not work. I have both workbench and kieserver subdirectories with Dockerfiles that simply extend the public images. I have not customized the images yet.

version: '2'
services:
  workbench:
   build: './workbench'
    ports:
      - "8080:8080"
  kieserver:
    build: './kieserver'
    links:
      - workbench:kie_wb
    ports:
      - "8081:8080"

Further research into docker compose says this is not a bug even though it breaks backward compatibility:
https://github.com/docker/compose/issues/2172
https://github.com/docker/compose/issues/2038

Here is a v1 docker-compose.yml which works correctly:

workbench:
  build: './workbench'
  ports:
    - "8080:8080"
kieserver:
  build: './kieserver'
  links:
    - workbench:kie_wb
  ports:
    - "8081:8080"

It seems that the auto-configure is based on the host name, however, this will not work in future versions of docker-compose because it uses DNS instead. My suggestion would be to improve the "auto-discovery" feature so it is less dependent on certain implementations. Perhaps an environment variable with the host name might suffice but then, the host name might not be available if the workbench hostname is set dynamically so some other discovery tool/technique might be needed. 

With jBPM 7 coming out, I hope maybe this can be addressed since there is even more emphasis on this controller/executor pattern. It has a lot of potential!

**Comment by jauffrey** [comment]
I managed to make those work on v 2+ of compose files. 
I just compared the container created with the docker run and the one created with compose (using version 3.2), and I figured out this: 
```
39c39
<             "NetworkMode": "default",
---
>             "NetworkMode": "bridge",
```
So I tried with the following compose file and it worked: 
```
version: '3.2'

services:
  drools-wb:
    image: jboss/drools-workbench-showcase:latest
    ports:
      - 8080:8080
      - 8001:8001
    environment: 
      - KIE_DEMO=false
      - M2_HOME=/maven/apache-maven-3.0.4
      - JAVA_OPTS=-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true
    volumes: 
      - /tools/maven:/maven
    network_mode: default
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "1"

  kie-wb:
    image: jboss/kie-server-showcase:latest
    ports: 
      - 8180:8080
    environment: 
      - JAVA_OPTS=-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true
    links: 
      - drools-wb:kie-wb
    network_mode: default
```
Note how I'm using a  `network_mode: default` which I don't see anywhere in the docs. 
Anyway, this setting seems to re-enable the use of the default bridge network and the services are discovered.

Anyway, this should not be the way to go. I've tried to use properly the network created by docker-compose, and tried to use the local DNS 127.0.0.11 inside the JVM like this: 
```
environment: 
      - JAVA_OPTS=-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true -Dsun.net.spi.nameservice.nameservers=127.0.0.11 -Dsun.net.spi.nameservice.provider.1=dns,sun
```
But I'm still stuck in discovery - even if the containers can communicate to each other. 

Any help appreciated, even if one can use the workaround in the meantime.
