### ISSUE TITLE
Support Apple Silicon (M1)

### ISSUE THREAD

**Issue by deathemperor** [jboss-dockerfiles/drools#60]
I've just started drools-wb and kie-server on M1 with this docker-compose.yml

```yml
version: '3'

services:
  drools-wb:
    container_name: drools-wb
    image: jboss/drools-workbench-showcase:latest
    ports:
      - 8001:8001
      - 28080:8080

  kie-server:
    container_name: kie-server
    image: jboss/kie-server-showcase:latest
    links:
      - drools-wb:kie_wb
    ports:
      - 8080:8080
    depends_on:
      - drools-wb
    environment:
      # KIE Workbench environment variables
      # Neccessary to connect the KIE server to the KIE workbench
      - KIE_WB_PORT_8080_TCP=tcp://kie_wb:8080
      - KIE_WB_ENV_KIE_CONTEXT_PATH=drools-wb
      - KIE_WB_PORT_8080_TCP_ADDR=kie_wb

```

Got this error.

```
drools-wb   | =========================================================================
drools-wb   |
drools-wb   | 15:41:05,187 INFO  [org.jboss.modules] (main) JBoss Modules version 1.8.6.Final
drools-wb   | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
kie-server  | Using 'kie-server-9b1099bf9020' as KIE server identifier
drools-wb   | *** JBossAS process (133) received SEGV signal ***
kie-server  | Detected successful link for KIE Workbench container. Applying automatic configuration for the link...
kie-server  | Using 'http://172.20.0.3:8080/kie-server/services/rest/server' as KIE server location
kie-server  | Using 'http://kie_wb:8080/drools-wb/rest/controller' as KIE server controller
kie-server  | Using 'http://kie_wb:8080/drools-wb/maven2' for the kie-workbench Maven repository URL
kie-server  | Running KIE Execution Server on JBoss Wildfly...
kie-server  | JAVA_OPTS already set in environment; overriding default settings with values: -Xms256m -Xmx1024m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8
kie-server  | =========================================================================
kie-server  |
kie-server  |   JBoss Bootstrap Environment
kie-server  |
kie-server  |   JBOSS_HOME: /opt/jboss/wildfly
kie-server  |
kie-server  |   JAVA: /usr/lib/jvm/java/bin/java
kie-server  |
kie-server  |   JAVA_OPTS:  -server -Xms256m -Xmx1024m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8  --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED
kie-server  |
kie-server  | =========================================================================
kie-server  |
drools-wb exited with code 0
kie-server  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
kie-server  | *** JBossAS process (222) received SEGV signal ***
```

I believe it has something to do with this known issue from Docker https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues

Please consider supporting M1
